### ISSUE TITLE
View update job already started error

### ISSUE THREAD

**Issue by luapascoal** [DevNatan/inventory-framework#106]
Error:
`[14:43:12 ERROR]: Could not pass event PlayerInteractAtEntityEvent to robots v1.0 org.bukkit.event.EventException: null at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1342) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312] at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] Caused by: java.lang.IllegalStateException: View update job already started at com.screennetwork.robots.libs.view.ViewUpdateJob.start(ViewUpdateJob.java:43) ~[?:?] at com.screennetwork.robots.libs.view.ScheduledViewContext.<init>(ScheduledViewContext.java:25) ~[?:?] at com.screennetwork.robots.libs.view.View.createContext(View.java:107) ~[?:?] at com.screennetwork.robots.libs.view.View.open(View.java:154) ~[?:?] at com.screennetwork.robots.libs.view.ViewFrame.open(ViewFrame.java:138) ~[?:?] at com.screennetwork.robots.listener.RobotListener.onClickEntity(RobotListener.java:123) ~[?:?] at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445] ... 16 more`

Apparently when there is someone in the inventory and someone else tries to access the same, this error is sent.
We use relocate in jar.

**Comment by DevNatan** [comment]
Fixed in [v2.5.1-rc.1](https://github.com/DevNatan/inventory-framework/releases/tag/2.5.1-rc.1)
