### ISSUE TITLE
get the item on onClickOutside

### ISSUE THREAD

**Issue by efefury** [DevNatan/inventory-framework#109]
hey, is there currently a way to get the item that's been clicked on with the `View#onClickOutside` method?

**Comment by DevNatan** [comment]
`onClickOutside` has no items involved, only the cursor item you can retrieve it by `player.getItemOnCursor()`.

Due to an mistake when creating this handler API, the parameter is ViewContext instead of a ViewSlotContext, that'll be fixed soon
