### ISSUE TITLE
[question] how to ue onClose()

### ISSUE THREAD

**Issue by guikaua12** [DevNatan/inventory-framework#126]
how do i use onClose() method

**Comment by DevNatan** [comment]
@guikaua12 You can use `onClose` to perform actions when a player closes the view's container, it supports canceling too, so if you cancel the `CloseViewContainer` the container will be opened again to the player.
```java
@Override
protected void onClose(CloseViewContext context) {
    /* ... do something ... */
    
    // container will be prevented from be closed
    context.setCancelled(true);
}
```

**Comment by guikaua12** [comment]
thanks
