### ISSUE TITLE
[question] how do i update a item like this image:

### ISSUE THREAD

**Issue by guikaua12** [DevNatan/inventory-framework#127]
how do i update a item when i click on it, like this:
![image](https://user-images.githubusercontent.com/33811154/177060369-b8768155-25ba-4e58-a9c9-8089490efc7a.png)
![image](https://user-images.githubusercontent.com/33811154/177060379-937e32dd-360f-4c0a-a928-4e784eddfad2.png)
![image](https://user-images.githubusercontent.com/33811154/177060384-7821e309-a6ce-4912-abee-e6a406592e21.png)
i tried this:
```private static ItemStack moeda1, moeda2, moeda3;
    private static final String CURRENT_MOEDA = "moeda1";
    public PagamentoMenu() {
        super(3, "Pagamento");
        setCancelOnClick(true);
        moeda1 = new ItemBuilder(Material.GOLD_NUGGET).setName("§fForma de pagament1").setLore("§amoeda1", "§7moeda2", "§7moeda3").toItemStack();
        moeda2 = new ItemBuilder(Material.GOLD_NUGGET).setName("§fForma de pagamento").setLore("§7moeda1", "§amoeda2", "§7moeda3").toItemStack();
        moeda3 = new ItemBuilder(Material.GOLD_NUGGET).setName("§fForma de pagamento").setLore("§7moeda1", "§7moeda2", "§amoeda3").toItemStack();
        slot(13).onRender(render -> {
            render.setItem(render.get(CURRENT_MOEDA, () -> moeda1));
        }).onClick(click -> {
            if(click.getItem().equals(moeda1)) {
                click.set(CURRENT_MOEDA, click.get(CURRENT_MOEDA, () -> moeda2));
                click.update();
            }
            if(click.getItem().equals(moeda2)) {
                click.set(CURRENT_MOEDA, click.get(CURRENT_MOEDA, () -> moeda3));
                click.update();
            }
        });
```
but it does not work after the second click

**Comment by DevNatan** [comment]
@guikaua12 You won't be able to compare like this: `click.getItem().equals(moeda1)`. `getItem` always returns a copy, wrapper or clone of the item. You must keep in context what the current selection index is, not the item in the selection. By saving the selection you can render the right item.

**Is extremely unrecommended to save complex objects in context**, ideally you save essentially primitive types that give you information to which object you want to reference. Example: if you want to save players, you save the player's name or their id, NOT THE PLAYER'S OBJECT.

This is an example using indexing from your code
```java
private static final String MAIN = "main",
    COMMERCE = "commerce",
    COMBAT = "combat",
    CURRENT = "selection";
    
private static final String[] ORDER = new String[] { MAIN, COMMERCE, COMBAT }; 
private static final ItemStack[] ITEMS = new ItemStack[] { moeda1, moeda2, moeda3 };

slot(13).onRender(render -> {
    // default selection is "main"
    final int currentSelectionIndex = render.get(CURRENT, () -> 0);
    
    // determines which item will be rendered depending on selection
    final ItemStack item = ITEMS[currentSelectionIndex];
        
    render.setItem(item);
});
```

And then you can handle click based on indexes too
```java
...onClick(click -> {
    // gets the current selection
    final int currentSelectionIndex = render.get(CURRENT, () -> 0);
    
    // determines what will be the next index of the item to be rendered
    final int nextSelectionIndex = currentSelectionIndex++;
   
    // prevent IOOBE (IndexOutOfBoundsException) on index
    final int fixedSelectionIndex = nextSelectionIndex == ITEMS.length ? 0 : nextSelection
        
    click.set(CURRENT_MOEDA, fixedSelectionIndex);
    click.update();
});
```

**Comment by guikaua12** [comment]
thank you
so the ViewContext is the same for the entire inventory?
I thought it changed by slot

**Comment by DevNatan** [comment]
> thank you so the ViewContext is the same for the entire inventory? I thought it changed by slot

ya, there is only one context per player for the entire lifecycle (as long as the container is open to it), slot contexts are just derivations that inherit everything from player context, containing only some extra properties like item and slot.

**Comment by guikaua12** [comment]
ok, thanks, really appreciate
