### ISSUE TITLE
NoSuchMethodError: me.saiintbrisson.minecraft.ViewFrame.open(Ljava/lang/Class;Lorg/bukkit/entity/Player;)Lme/saiintbrisson/minecraft/AbstractView;

### ISSUE THREAD

**Issue by guikaua12** [DevNatan/inventory-framework#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

The view is completely empty as shown below:
![image](https://user-images.githubusercontent.com/33811154/179374726-22cb358d-7a2e-4185-af6a-901ab5f462e1.png)

The error:
```
Caused by: java.lang.NoSuchMethodError: me.saiintbrisson.minecraft.ViewFrame.open(Ljava/lang/Class;Lorg/bukkit/entity/Player;)Lme/saiintbrisson/minecraft/AbstractView;
        at me.approximations.heat.spawners.listener.MenuOpenListener.onInteract(MenuOpenListener.java:39) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        ... 17 more
```

The view register: 
![image](https://user-images.githubusercontent.com/33811154/179374756-2a278efc-9b39-45ef-beff-04dd2cf7aecc.png)

### ✔️ Expected behavior

Open the menu

### 👣 Steps to Reproduce

Idk, the view class is empty

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Version

1.8.8

**Comment by luiz-otavio** [comment]
Do you have any plugins in the same folder which is using `inventory-framework`? Most of thos exception are triggered from situations where the classpath in the runtime is different from the code.

**Comment by DevNatan** [comment]
You must shade IF in your project as a library or use IF plugin for your platform.
See: [Installation Guide on Wiki](https://github.com/DevNatan/inventory-framework/wiki/Installation) also [Preventing Library Conflicts](https://github.com/DevNatan/inventory-framework/wiki/Installation#preventing-library-conflicts)

**Comment by guikaua12** [comment]
> Do you have any plugins in the same folder which is using `inventory-framework`? Most of those exceptions are triggered from situations where the classpath in the runtime is different from the code.

Yes i have, i downgraded to the 2.5CC version, as it is stable.



> @guikaua12 You must shade IF in your project as a library or use IF plugin for your platform. See also [Installation Guide on Wiki](https://github.com/DevNatan/inventory-framework/wiki/Installation) and [Preventing Library Conflicts](https://github.com/DevNatan/inventory-framework/wiki/Installation#preventing-library-conflicts).

I don't use Maven our Gradle, i just import the jar file to my project

**Comment by luiz-otavio** [comment]
> > Do you have any plugins in the same folder which is using `inventory-framework`? Most of those exceptions are triggered from situations where the classpath in the runtime is different from the code.
> 
> Yes i have, i downgraded to the 2.5CC version, as it is stable.
> 
> > @guikaua12 You must shade IF in your project as a library or use IF plugin for your platform. See also [Installation Guide on Wiki](https://github.com/DevNatan/inventory-framework/wiki/Installation) and [Preventing Library Conflicts](https://github.com/DevNatan/inventory-framework/wiki/Installation#preventing-library-conflicts).
> 
> I don't use Maven or Gradle, i just import the jar file to my project

Great. I would like if you could use a build tool like Maven or Gradle, since those issues happen eventually.

If it's marked as resolved, please, close the issue <3
