### ISSUE TITLE
IllegalStateException when use setSource in PaginatedView

### ISSUE THREAD

**Issue by eokasta** [DevNatan/inventory-framework#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

When an inventory is opened defining the setSource it says that it has not been defined.

### ✔️ Expected behavior

Register the Source and open the paginated inventory with the objects.

### 👣 Steps to Reproduce

![image](https://user-images.githubusercontent.com/60123043/180083009-5d32ffe4-2f5a-4fdc-89ee-06d236da924b.png)
![image](https://user-images.githubusercontent.com/60123043/180083223-8ea72c56-fd93-44f4-b526-ddb240ab18df.png)

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Version

1.8

**Comment by luiz-otavio** [comment]
Does the same thing happen if you override `onOpen` method to do that?
