### ISSUE TITLE
UnsupportedOperationException when use getPlayer in PaginatedViewSlotContext

### ISSUE THREAD

**Issue by kauepalota** [DevNatan/inventory-framework#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

When you try to use getPlayer in PaginatedViewSlotContext it throws a UnsupportedOperationException 

### ✔️ Expected behavior

It should return the player who opened the view

### 👣 Steps to Reproduce

![image](https://user-images.githubusercontent.com/51864067/181395879-2bd6a6a9-13a6-44b5-940a-86f5332422d0.png)
![image](https://user-images.githubusercontent.com/51864067/181396181-e7d4d9ca-7263-4926-8f0e-54c8ac9e2998.png)

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

MC 1.8.9, IF 2.5.2

**Comment by DevNatan** [comment]
@kauepalota Being worked on #183. You download the new possibly fixed artifact from [**Generate Artifacts**](https://github.com/DevNatan/inventory-framework/actions/runs/2757875013) workflow (scroll down) or try out [`5bfb11ad26`](https://jitpack.io/#DevNatan/inventory-framework/5bfb11ad26) library version.
