### ISSUE TITLE
setSource error

### ISSUE THREAD

**Issue by luapascoal** [DevNatan/inventory-framework#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

setting the source in onRender an error appears

![image](https://user-images.githubusercontent.com/55550262/182979420-6a8881d8-2120-4713-a8a1-ff4048746b5b.png)
![image](https://user-images.githubusercontent.com/55550262/182979495-7572a9d3-ab4b-4188-ae36-03d9580978f7.png)

### ✔️ Expected behavior

...

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

1.8.9

**Comment by DevNatan** [comment]
Fixed in #201
