### ISSUE TITLE
Dúvida em relação a paginação

### ISSUE THREAD

**Issue by BADnotice** [DevNatan/inventory-framework#21]
Olá, estou com uma dúvida em relação ao setar o item de ir para a próxima página e voltar usando o inventário paginado, como faço para definir eles?

**Comment by DevNatan** [comment]
> Olá, estou com uma dúvida em relação ao setar o item de ir para a próxima página e voltar usando o inventário paginado, como faço para definir eles?

Você pode definir por *View* ou globalmente através do ViewFrame.

Definir globalmente fará com que o item seja o mesmo pra todos as *View*s que você criar.
```java
viewFrame.setDefaultPreviousPageItem((context) -> item(Material.ARROW));
viewFrame.setDefaultNextPageItem((context) -> item(Material.ARROW));
```

Ou por *View*, irá se aplicar somente àquela *View* em específico.
```java
public final class MyView extends View {

    @Override
    public final ViewItem getPreviousPageItem(final ViewContext context) {
        return item(Material.ARROW);
    }

    @Override
    public final ViewItem getPreviousNextItem(final ViewContext context) {
        return item(Material.ARROW);
    }

}
```

Caso esteja usando uma PaginatedView você pode usar os caracteres `<` (representa página anterior) ou `>` (representa próxima página), que os itens serão definidos na sua View sem necessidade de colocação manual.
```java
... no construtor da sua Paginated View
setLayout(
    "XXXXXXXXX"
    "<OOOOOOO>"
    "XXXXXXXXX
)
...
```

As função de ***click*** é definida automáticamente

**Comment by BADnotice** [comment]
Deu certo obrigado! outra dúvida, tem algum método que só faz aparecer os itens de ir para outra pagina e voltar caso tenha outras paginas?

**Comment by DevNatan** [comment]
> Deu certo obrigado! outra dúvida, tem algum método que só faz aparecer os itens de ir para outra pagina e voltar caso tenha outras paginas?

Se você retornar `null` nas funções de paginação o item some. Você pode usar a extensão `paginated()` em conjunto de `hasPreviousPage()` e `hasNextPage()` pra decidir se vai exibir o item ou não.

**Exemplo: o item de "Próxima página" só vai ser exibido se houver uma próxima página.**
```java
@Override
public final ViewItem getNextPageItem(final ViewContext context) {
  return context.paginated().hasNextPage() ? item(Material.ARROW) : null;
}
```

Também funciona com as funções padronizadas.
```java
viewFrame.setDefaultNextPageItem((context) -> {
  return context.paginated().hasNextPage() ? item(Material.ARROW) : null;
});
```

**Comment by BADnotice** [comment]
Se retornar ``null`` usando o layout ele não encontra um item e retorna ``IllegalArgumentException``.

Codigo
![image](https://user-images.githubusercontent.com/73367676/150569682-3139019b-25be-4220-93dd-86e41c072de3.png)

Erro
![image](https://user-images.githubusercontent.com/73367676/150569747-23acb3ab-39ff-458a-abe6-566e44e91bbc.png)

Layout
![image](https://user-images.githubusercontent.com/73367676/150569786-c4b8db96-151c-4fef-977b-d651980aa80d.png)

**Comment by TakuiasH** [comment]
![image](https://user-images.githubusercontent.com/59321488/150581705-a16a4117-fd28-4102-9471-d6c30869ed2f.png)
Eu estou sem saber oq fazer após isso :(
