### ISSUE TITLE
Data not being spread on Paginated View

### ISSUE THREAD

**Issue by zAlyson** [DevNatan/inventory-framework#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

I suppose that this only happens on Paginated View for now, haven't tried it on normal view yet!

When I set a data when opening a paginated view, I can't read that data on `onItemRender` (It was possible on the previous version), but it is readable on `onRender`.

What I mean by can't read the data, is that it's not there.

### ✔️ Expected behavior

The data to be spread  🤷‍♂️

### 👣 Steps to Reproduce

Create a class extending `PaginatedView<>`
Open the view and define any data
Try to read those data in `onItemRender`

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

1.8.9

**Comment by DevNatan** [comment]
@zAlyson thx 👍🏽
