### ISSUE TITLE
Can not switch pages

### ISSUE THREAD

**Issue by zAlyson** [DevNatan/inventory-framework#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

The pages on paginated view can't be switched when sources are dynamic set.

![image](https://user-images.githubusercontent.com/45720313/187431776-e81cea36-2ec2-4232-bdb4-4a3ffc7f0065.png)

### ✔️ Expected behavior

Switch between pages when sources are dynamic set. 

### 👣 Steps to Reproduce

1. Create a Paginated View
2. Set the source dynamically
3. Try to switch pages

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

MC 1.8.9, IF v2.5.4-beta

### ✍️ Additional context

The sources are being set on the `onRender` function.

**Comment by zAlyson** [comment]
Are you planning to solve this within the next days or so?

**Comment by DevNatan** [comment]
> Are you planning to solve this within the next days or so?

i don't have much time right now but the PR with the fix (#228) is done

**Comment by zAlyson** [comment]
The PR did not fix the issue sadly. 
 
_Here's a video demonstrating the bug:_

https://user-images.githubusercontent.com/45720313/189335734-ebd5bff0-b8a1-4027-8962-944f619bf4dd.mp4

**Comment by DevNatan** [comment]
Fixed in https://github.com/DevNatan/inventory-framework/commit/b1f17f0b03000c00ea4be878ff068c23aa33f3c3
