### ISSUE TITLE
Função onClick está duplicando seu callback

### ISSUE THREAD

**Issue by TakuiasH** [DevNatan/inventory-framework#24]
Toda vez que clico no item ele duplica tudo que esta dentro da função

![image](https://user-images.githubusercontent.com/59321488/150589107-b3e87408-ff82-4fdf-89b1-387c54605828.png)

**Comment by DevNatan** [comment]
Geralmente isso acontece quando o ViewFrame é registrado duas vezes.

Você teria como me mostrar o código do completo (da View inteira), e de preferência, quando o ViewFrame é registrado pra que seja possível eu reproduzir o erro?

**Comment by TakuiasH** [comment]
Aqui está!
https://imgur.com/a/nmfijAF

**Comment by TakuiasH** [comment]
Lembrando q estou usando a api da spigot 1.18

**Comment by luiz-otavio** [comment]
Estou tendo o mesmo problema na versão `2.3.1`...

**Comment by luiz-otavio** [comment]
#36 deve resolver esse problema.
