### ISSUE TITLE
java.lang.IllegalStateException: Pagination source can only be set once. If you need dynamic source use pagination source provider or asynchronous pagination source instead.

### ISSUE THREAD

**Issue by guikaua12** [DevNatan/inventory-framework#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

Basically, i need to dinamically update the source on update, as i 'm doing rn, but its throwing that error
`java.lang.IllegalStateException: Pagination source can only be set once. If you need dynamic source use pagination source provider or asynchronous pagination source instead.`
<img src="https://b.catgirlsare.sexy/CAHnHEJrdHyH.png">

### ✔️ Expected behavior

The source be updated with the new source

### 👣 Steps to Reproduce

1 - Set the source on render
2 - On update, set the source again

### 💻 Platform

- [x] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

MC 1.8.8, IF 2.5.4-rc1

**Comment by DevNatan** [comment]
pagination source can only be set on constructor or first render (onRender).

there's no need to set it on update handler since it's computed, being computed, on each update the paginated data will be updated accordingly, just set it on constructor once
```java
setSource(context -> {
    context.paginated().setSource(getSpawner<Spawner>(context).getAmigos());
});
```

**Comment by guikaua12** [comment]
The problem is that i want to update the source wheni do something, like on the video: https://www.youtube.com/watch?v=V4-vbEJDhpU

**Comment by zAlyson** [comment]
Have you got it working? You just need to put that code on `onRender`. I've done something similar with no problem.

**Comment by guikaua12** [comment]
> 

I will try it

**Comment by guikaua12** [comment]
> Have you got it working? You just need to put that code on `onRender`. I've done something similar with no problem.

Nah, it didn't update the source
https://www.youtube.com/watch?v=uiAcJEBXFoY

**Comment by DevNatan** [comment]
> > Have you got it working? You just need to put that code on `onRender`. I've done something similar with no problem.
> 
> Nah, it didn't update the source https://www.youtube.com/watch?v=uiAcJEBXFoY

make sure u call `update()` player head interaction

**Comment by guikaua12** [comment]
> > > Have you got it working? You just need to put that code on `onRender`. I've done something similar with no problem.
> > 
> > 
> > Nah, it didn't update the source https://www.youtube.com/watch?v=uiAcJEBXFoY
> 
> make sure u call `update()` player head interaction

Yeah, i'm calling `update`
<img src="https://b.catgirlsare.sexy/Jm1hrKnlcgua.png">

**Comment by DevNatan** [comment]
@guikaua12 seems like a strange interaction, can you confirm that the friends list is actually being updated when you remove it? i'll try to reproduce something similar

**Comment by guikaua12** [comment]
> @guikaua12 seems like a strange interaction, can you confirm that the friends list is actually being updated when you remove it? i'll try to reproduce something similar

yes, it is being updated, as you can see in the videos i linked in the comments

**Comment by DevNatan** [comment]
i couldn't reproduce the problem, can you send me more parts of the code for analysis?

**Comment by guikaua12** [comment]
> i couldn't reproduce the problem, can you send me more parts of the code for analysis?

yo, i fixed the problem, the problem was that i was using `setSource()` in the `onClick`, i fixed it using `setSource()` in the render method itself

**Comment by guikaua12** [comment]
> i couldn't reproduce the problem, can you send me more parts of the code for analysis?

yo, i fixed the problem, the problem was that i was getting the Spawner object in the `onClick()` instead of in the render method itself
