### ISSUE TITLE
View updating but not updating (??)

### ISSUE THREAD

**Issue by guikaua12** [DevNatan/inventory-framework#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

I don't know if its my issue or IF issue

Here is a screenshot of my code: https://b.catgirlsare.sexy/IzDFI4UTPxp8.png
Here is a video showing the issue: https://www.youtube.com/watch?v=EXqKzRVE6sA
Please watch until the end

### 👣 Steps to Reproduce

1- Update the view

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

MC 1.8.8 IF 2.5.4 rc-1

**Comment by zAlyson** [comment]
What you're doing is not ideal at all. What you should do first is to move your code from **onUpdate** to **onRender** and then set the slot this way: `context.slot(...).rendered(() ->  **item aqui**).onClick(clickContext ->  **lógica aqui**);`

**Comment by guikaua12** [comment]
> What you're doing is not ideal at all. What you should do first is to move your code from **onUpdate** to **onRender** and then set the slot this way: `context.slot(...).rendered(() -> **item aqui**).onClick(clickContext -> **lógica aqui**);`
Partially fixed, but the itemstack does not update now
Video:
https://youtu.be/h15VK7MgqAI
Code:
<img src="https://b.catgirlsare.sexy/GlqV4_sxHWze.png">

**Comment by guikaua12** [comment]
I did this way and it worked: <img src="https://b.catgirlsare.sexy/UVZKnsCnRjeS.png">

**Comment by zAlyson** [comment]
It's how it needs be though 😅

**Comment by guikaua12** [comment]
Thank you for the help 😍
