### ISSUE TITLE
[RFC] Async function pre render

### ISSUE THREAD

**Issue by Lipe567** [DevNatan/inventory-framework#283]
### First, a few things...

- [ ] Is your feature request related to a problem?
- [X] Will this feature just help you or is it something everyone needs?
- [ ] Have you tried to implement or *draft* this feature?
- [ ] Is your feature a breaking change?

### 😄 Describe the solution you'd like

How long natan, your library is great but I missed an async function before the page is rendered, to be able to render things fetched from the database without lag for the main thread, in that function it wouldn't be possible to modify anything in the inventory yet. just add data using setData

### 🧠 Describe alternatives you've considered

implement a function onPreOpenAsync and onPreRenderAsync

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other
- [ ] All

### ⭐ Version

v2.5.4-rc.1

**Comment by saiintbrisson** [comment]
The proposal isn't clear on how to proceed after calling the async handler. Does the framework wait until the async handler finishes and then opens? Does it call for a refresh afterward? If the former, how do we handle it? If the latter, it's already pretty straightforward to pull.
Adding asynchronous support to a library that deals with primarily synchronous code is messy and I'd personally advise against it.

Thoughts @DevNatan?

**Comment by saiintbrisson** [comment]
> it's already pretty straightforward to pull off.

Developing on this affirmation: it's common for UI frameworks to support `skeletons`. You open the UI (inventory) first even if data isn't yet loaded, and make it explicit that things will appear in the next second or so. IMO, this is the way to go, the user becomes aware that things are happening in the background, and doesn't have to wait until the inventory appears, which can be frustrating.

Currently, you can easily spawn a future from within the `onPre*` and call for a refresh when things are ready. The one change we can maybe do is making the refresh function thread-safe and ensuring it's called from the main thread, on the contrary, schedule a sync task.
