### ISSUE TITLE
How to import v3.0.0?

### ISSUE THREAD

**Issue by Azodox** [DevNatan/inventory-framework#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

Hello 👋🏻,

I've recently tried to import latest version of IF in my project.
I was about to make my best astonishing inventory self-updated. Unfortunately, I couldn't remember how to do so.

Therefore, I looked up the documentation and inform myself through it. However, when I tried what the documentation told me to do in my code, it didn't find the required classes. 
Feeling surprised, I searched everywhere a reason and attempted other versions, I even used commits code or even "main-SNAPSHOT", but still. 
Desperate, I suddenly put one's finger on something: when importing the following dependencies : `'com.github.DevNatan:inventory-framework:836c14608b'`, it only imports the api and the rest is left empty whereas it is present as a dependency in the "External Librairies" tab.

(Thank you in advance, sorry if you take it as sarcasm)

Here is a screenshot:
![image](https://user-images.githubusercontent.com/52888902/227041701-3c8c9168-aeab-4254-8cd1-8299582ca4d7.png)

 

### ✔️ Expected behavior

Well, I guess I'm supposed to have all the necessary files, which is not the case here.

### 👣 Steps to Reproduce

1. Just import this dependency : `'com.github.DevNatan:inventory-framework:836c14608b'`

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [X] Other

### ⭐ Versions

1.19.3 + IF 836c14608b

### ✍️ Additional context

You know me, I'm on Paper ✊🏻

**Comment by Azodox** [comment]
Alright, thanks!

**Comment by DevNatan** [comment]
3.0.0-beta and release candidates (3.0.0-RC*) will be published on Jitpack. 3.0.0 final release will be published on Maven Central

**Comment by DevNatan** [comment]
[v3.0.0-EAP](https://github.com/DevNatan/inventory-framework/releases/tag/v3.0.0-EAP) is now available on Maven Central Snapshots Repository
