### ISSUE TITLE
Setar item na linha *6* do inventário utilizando o método por especificação de row e column retorna exception.

### ISSUE THREAD

**Issue by zAlyson** [DevNatan/inventory-framework#32]
![image](https://user-images.githubusercontent.com/45720313/151052207-19a400f5-bf5b-4886-b123-c7e1aefdee9c.png)

Utilizando o primeiro método da imagem o código será executado com êxito, mas, se por acaso, utilizar o segundo método, irá retornar a seguinte exception: **java.lang.IllegalArgumentException: Row cannot be greater than 6**

_Obs: Linha 6 e coluna 3 representam o slot 47_

**Comment by DevNatan** [comment]
Fixed in https://github.com/DevNatan/inventory-framework/commit/ae3fa38ac7ff18f863f3a43de11b85400164ca09 and is now available on v2.4.0.
