### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by gabrideiros** [DevNatan/inventory-framework#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

Basically I'm trying to get the amount of total pages in onFirstRender or onOpen, but it gives an error, because it looks like the pages haven't been created yet.

![image](https://github.com/DevNatan/inventory-framework/assets/54453020/6f64e07c-7a27-4b8f-b2af-9260a1a15da3)

I believe that the error must be here, because of the order, but I can't fix it
![image](https://github.com/DevNatan/inventory-framework/assets/54453020/21cf8301-5636-4e4b-8303-0de92171e914)

### ✔️ Expected behavior

none

### 👣 Steps to Reproduce

none

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

MC 1.20.1

**Comment by DevNatan** [comment]
Fixed in #399
