### ISSUE TITLE
update title for player not work

### ISSUE THREAD

**Issue by ch4ika** [DevNatan/inventory-framework#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

Use         
context.updateTitleForPlayer("TEST"); onClick.

Info: Also used the Trade Plugin in your example.

https://www.toptal.com/developers/hastebin

### 💻 Platform

- [x] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Server Version

Current: git-Purpur-2028 (MC: 1.20.1)* Previous: git-Purpur-2023 (MC: 1.20.1) * You are running the latest version

### 📚 Library Version

3.0.0-rc.1

**Comment by DevNatan** [comment]
Unfortunately #updateTitleForPlayer() and #resetTitleForPlayer() do not support MC 1.19 and 1.20 yet.
Being implemented in #423 and will become available in v3.0.0-rc.2 (08 Aug 2023)
